name: Update LIG1 Buy Price

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug â€“ list files
        run: |
          echo "ROOT:"
          ls -la
          echo ""
          echo "SCRIPTS:"
          ls -la scripts || echo "scripts folder not found"

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install ethers

      - name: Run buy price script
        run: node scripts/fetchprice.js
